language: node_js
node_js:
  -  "5.11"
before_script:
  - npm install -g gulp
  - npm install
script:
  - gulp 

deploy:

  provider: heroku

  app: tips-pdes

  api_key:

    secure: $HEROKU_API_KEY
  on:
    tags: true
