language: node_js
node_js:
  -  "5.11"
before_script:
  - npm install -g gulp
  - npm install
script:
  - webdriver-manager update
  - webdriver-manager start
  - gulp tests_backend
  - gulp tests_frontend
  - gulp tests_e2e
